pipeline {
    agent any
    tools { 
        maven 'maven' 
        jdk 'java1.8-211' 
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' 
            }
        }

        stage ('scm') {
            steps {
                git credentialsId: 'a414caca-ec49-4775-8431-65187c1febe6', url: 'https://github.com/praveenthoutam/project1.git'
            }
        }
        
        stage ('build') {
	   steps {
                sh 'mvn clean install'
            }
		}
    }
}
